# Generated by Django 3.2.8 on 2021-12-29 04:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
